set -g default-terminal "screen-256color"
# set -ga terminal-overrides ",screen-256color*:Tc"
set -s escape-time 0

# Unbind <C-b> as the prefix key
unbind C-b

# Bind <C-a> as the prefix key
unbind C-a
set-option -g prefix C-a
# bind-key C-a send-prefixset -g status-style 'bg=#333333 fg=#5eacd3'

# unbink k
# bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded 🚀"

# start index from 1
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Enable vim keys for copy mode
set-window-option -g mode-keys vi

bind V copy-mode
bind -T copy-mode-vi V send-keys -X cancel

unbind -T copy-mode-vi v

bind -T copy-mode-vi v \
  send-keys -X begin-selection

bind -T copy-mode-vi 'C-v' \
  send-keys -X rectangle-toggle

bind -T copy-mode-vi y \
  send-keys -X copy-pipe-and-cancel "pbcopy"

bind -T copy-mode-vi MouseDragEnd1Pane \
  send-keys -X copy-pipe-and-cancel "pbcopy"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R



#
# tpm plugin manager
set -g @plugin "tmux-plugins/tpm"

# Plugin to make tmux more sensible
set -g @plugin 'tmux-plugins/tmux-sensible'

# Plugin to install catppuccino theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'macchiato' 
#
# Initalize tpm (this needs to be the last line)
run "~/.config/tmux/plugins/tpm/tpm"
